### ISSUE TITLE
Nexus is still not working.

### ISSUE THREAD

**Issue by PabloB07** [CrystallDEV/PlayerNPCLib#16]
Hey, nice to meet you, yor nexus is not working... i can't use your maven PlayerNPCLib to my plugin. :( im using 1.20.4 paper-api

Whats wrong?, please help.

![image](https://github.com/CrystallDEV/PlayerNPCLib/assets/36685434/532bb4e8-a299-4f28-b207-e870dd554683)

Thank you!

**Comment by CrystallDEV** [comment]
Hey @PabloB07,
thank you for reporting. I will fix this within the next days.

**Comment by PabloB07** [comment]
Thank you so much, dear Crystall glad to hear!


Cheers~
